### PR TITLE
Generalise functions to be N-dimensional

### PR DESCRIPTION
**Pull request by brmather**
Derivatives in `sTriMesh` are in 3 dimensions, which motivates a generalisation of some functions to accept 2 or 3 input arguments.

If no direction is provided to obtain derivatives, i.e.
```python
lazyFn.fn_gradient(dirn=None)
```
then all directional derivatives are returned (as functions).

### CODE REVIEW

**Comment by lmoresi** [comment]
I find it one of the oddest quirks of stripack that it returns Cartesian gradients for the 2D surface of a sphere and we wrapped that in stripy to make it only available if the user was knowledgeable enough to know that they wanted gradients that are not tangent to the surface. Are you sure this is a good idea ? @rbeucher, what is your feeling here as somebody who has not become indoctrinated with the ways of stripy ?

**Comment by brmather** [comment]
The `grad` function is a bit problematic when it comes to evaluate the derivatives in each direction. Because it returns a separate functions, the derivatives in the other directions are thrown away. It is essentially evaluating the derivatives twice for the `TriMesh` case, and thrice for the `sTriMesh`!

Not sure how to remedy this situation. It might be better to return a vector function like:

https://github.com/underworldcode/quagmire/blob/e78db6990401537929b2109f77ddee47430c13c1/quagmire/function/function_classes.py#L141-L166

(currently not being used)

**Comment by lmoresi** [comment]
OK - so there are two different issues really. One is the Cartesian gradient that stripack returns which (in my view) should usually be hidden away, and the other is that we don't handle vector functions very well at this point. 

I'm more tempted here to implement a scalar "slope" function and a scalar "laplacian" function that hide the details so that the surface of the sphere and the cartesian plane are equivalent. 

John's sympy vector stuff would be useful here, of course.

**Comment by brmather** [comment]
That seems fine to me. We can present the derivatives in lon lat directions from stripy's `gradient_lonlat` method, and I like the idea of a `slope` function. That will be more efficient. While we're on this subject... since we're evaluating the slope a lot (stream power, flood fill, landscape analysis) does it make sense to store slope as a mesh variable that gets re-evaluated when the topography is updated?

**Comment by lmoresi** [comment]
It may well be useful to have it as a meshvariable, yes ... I guess the fact that mesh variables and functions are equivalent means that we can define it as a function and over-ride  / replace that with a mesh variable without breaking any python methods that use it. Right ? 

(That is something we can make detailed decisions about when we see the overall performance. Caching in general is something that the functions are not great at doing in their present form. Hence the desire to have sympy simplify and John's JIT compiler stuff).

**Comment by brmather** [comment]
> It may well be useful to have it as a meshvariable, yes ... I guess the fact that mesh variables and functions are equivalent means that we can define it as a function and over-ride / replace that with a mesh variable without breaking any python methods that use it. Right ?

Exactly! They're all LazyEvaluation objects at heart. True to their school like the beach boys.

I've included a `slope` function, and the performance improvement is exactly what you'd expect:
Screenshot_2020-04-29 Ex1b-QuagmireLazyFunctions

It takes half the time because it's computing the gradient just once. The Cartesian derivatives from stripy are computed by a hidden method on the `sTriMesh` class. This means a duplicate method is required on the `TriMesh` and `PixMesh` class in order for the `slope` function to be compatible with them all, but I don't think this matters too much since they're not exposed to the user.

**Comment by lmoresi** [comment]
OK - looks reasonable. I think the reason I had not previously implemented this is that I was not sure how to implement the item selection in a lazy-evaluation context ... will it work if I say something like:

```
    my_annoying_fn = fn.math.sin(mymeshvar.fn_gradient[1]**2) 
    my_original_fn = fn.math.sin(mymeshvar.fn_gradient(dirn=1)**2) 
```

**Comment by brmather** [comment]
`my_annoying_fn` won't work. The method needs to be callable in case you want to interpolate onto a different mesh or set of coordinates. But this will work:
```python
my_annoying_fn = fn.math.sin(mymeshvar.fn_gradient()[1]**2) 
```
because separate functions for derivatives in all directions are returned if `dirn` is not specified.

`my_annoying_fn` could work if we define getter/setters for `fn_gradient`, but then you sacrifice interpolation...

**Comment by lmoresi** [comment]
That should be OK, I think - it's not that bad an expression to teach people. The only issue will be the compatibility with the uw interface.

**Comment by lmoresi** [comment]
Feel free to merge !

**Pull request merged**
