### PR TITLE
Clean the functions, remove the mesh dependency etc.

### PR DESCRIPTION
**Pull request by rbeucher**
1. Remove mesh from LazyEvaluation class
2. fn_gradient method is only available from the MeshVariable class.
3. Change arg name LazyFn to MeshVar where appropriate
4. Change shape of array returned by the `derivative_grad` methods. (All
   meshes). This to be consistent with the shape of `mesh.data`. Also
   consistent with Underworld.
5. Evaluation on coordinates requires passing a list, or numpy array of
   shape (n, 2). Again this is for consistency with UW...
6. Update tests to account for changes. All tests passing.

### CODE REVIEW

**Comment by rbeucher** [comment]
Argh I messed up with stripy. I'll fix that.

**Comment by lmoresi** [comment]
What about the evaluation on a mesh - does that still work like U/W ?
On 19 Jun 2020, 10:14 AM +1000, Romain Beucher <notifications@github.com>, wrote:

Argh I messed up with stripy. I'll fix that.

**Comment by rbeucher** [comment]
I am going to add some tests to make sure that it does.

**Comment by brmather** [comment]
It was decided in #14 that getting derivatives like

```python
mymeshvar.fn_gradient[1]
```

was better than

```python
mymeshvar.fn_gradient()[1]
```

hence I wrote that LazyGradientEvaluation class. It's more similar to UW too, right?

**Comment by rbeucher** [comment]
I think the UW method is `fn_gradient()[0]` I will check that.
Happy to revert. Don't look at that PR as ready. I am still exploring things...

**Comment by rbeucher** [comment]
So the behavior is slightly different than UW2.

meshVar.evaluate() will evaluate on the entire mesh by default (UW2 throws a RunTimeError)
meshVar.evaluate(0., 0.) will raise an error, you explicitly need to pass coordinates in a form of a list, tuple or numpy array:
meshVar.evaluate([0., 0.])
The code will interpolate the values if necessary. That is conform to UW2

meshVar.evaluate(mesh) evaluate on the mesh as expected. if the mesh passed as argument is different than the mesh the variable is built on, this triggers interpolation.

**Comment by lmoresi** [comment]
I don't have objections ... the UW differences were deliberate, I suspect, after much agonised discussion between Ben and me

**Comment by brmather** [comment]
I'm reopening this PR because we have an issue with daisy-chaining derivatives. I'm don't think it's a problem related to removing the mesh - so long as a mesh is supplied to the evaluate method i.e. `evaluate(mesh)` it should be fine - but `fn_gradient` must reside on all `LazyEvaluation` objects. Not just limited to mesh variables. This is so operator overloading works as intended.

Example 1b in the community repo has workflows to test all of this. I should get the tests to run those tutorials since they are now just jupytext python files.

**Comment by rbeucher** [comment]
OK. I can have a look at that. Yes adding the examples to the tests would be a good idea.
Lets discuss that.

**Comment by brmather** [comment]
Thanks @rbeucher! In the meantime I'll add more tests to this PR that summarises some of the expected behaviour from Ex1b.

**Comment by brmather** [comment]
I was hoping my new commits would show up here, but they do not. Instead they're at #37

**Pull request merged**
