### PR TITLE
QuagMesh - one object to rule them all

### PR DESCRIPTION
**Pull request by brmather**
Two major breaking changes in this PR:

#### 1. `FlatMesh`, `TopoMesh`, `SurfaceProcessMesh` have all been superseded by `Quagmesh`

- Clearer for users to choose just one mesh type
- Downhill matrices are only built when the topography is initialised, so there is no performance hit if all you want to do is play around with interpolation / gradients etc.
- `QuagMesh` will be documented once actions deploys the pdoc on the dev branch. It is clear where it inherits from.
- The underling mesh data structures i.e. `PixMesh`, `TriMesh`, `sTriMesh` are still exposed (albeit under the `mesh` sub-module), so it's possible to dig down into the code.

#### 2. Gradient operations are accessed by the property `fn_gradient`

- Now use `fn_gradient[0]` or `fn_gradient[1]` to access derivatives in the x and y directions, respectively.
- `fn_gradient` with no item selection returns a `LazyGradientFunction` which inherits from `LazyFunction`. Calling `.evaluate()` returns both derivatives.
- More similar to Underworld's implementation, which I think is intuitive.

### Changes to notebooks, scripts, etc.

All instances of `fn_gradient(dirn=0)` need to be replaced by `fn_gradient[0]` and any instances of `FlatMesh`, `TopoMesh`, `SurfaceProcessMesh` need to be replaced by `QuagMesh`. I suggest we create a quagmesh branch in the [community repo](https://github.com/underworld-community/quagmire-examples-and-workflows) to deal with these changes.

### CODE REVIEW

**Comment by brmather** [comment]
Resolves #14 
Resolves #15 
Resolves #17

**Comment by lmoresi** [comment]
1) Can we still do higher order derivatives with the new approach ? It should be possible to do this numerically even if accuracy is not optimal. 

2) parameters and constants should be able to support derivatives and interpolation (which are all zero, obviously) even if they have no mesh associated. In the original implementation that was not done so well and feels broken. Can we fix that / have we fixed that in quagmesh ?

3) Does the quagdf5 format depend on petsc+hdf5 or is it only h5py ?

**Comment by rbeucher** [comment]
The HDF outputs relies on Petsc. 
I would add the option to generate an XDMF directly from the save method. What do you think?

**Comment by brmather** [comment]
> Can we still do higher order derivatives with the new approach ? It should be possible to do this numerically even if accuracy is not optimal.

Yes you can daisy chain the derivatives like so:
```python
d3x = topography.fn_gradient[0].fn_gradient[0].fn_gradient[0]
```
It isn't supported for `fn_gradient` without item selection, because the number of returned derivatives would soon pile up. But it could be supported if that's what is needed.

> parameters and constants should be able to support derivatives and interpolation (which are all zero, obviously) even if they have no mesh associated. In the original implementation that was not done so well and feels broken. Can we fix that / have we fixed that in quagmesh ?

We should fix that, I haven't touched the parameter stuff yet. At the very least it should have the same `fn_gradient` interface as above.

> Does the quagdf5 format depend on petsc+hdf5 or is it only h5py ?

Yes it needs petsc+hdf5 so that all the DM labels and attributes can be loaded up on import, unfortunately #10 is not yet resolved.

**Comment by lmoresi** [comment]
I'm good with this - as discussed earlier: make a compatibility release to the master branch so that  the community repo will continue to function with that code while we adapt the notebooks there.

**Comment by brmather** [comment]
Parameter functions are now fixed. Merging...

**Pull request merged**
