### PR TITLE
Add conditional function

### PR DESCRIPTION
**Pull request by rbeucher**
Adds conditional function. Needs testing...

Essentially works like the UW version...

### CODE REVIEW

**Comment by brmather** [comment]
I like the conditional stuff, could you add a demo in the [LazyFunctions tutorial](https://github.com/underworld-community/quagmire-examples-and-workflows/blob/master/Examples/Tutorial/Ex1b-QuagmireLazyFunctions.py)?

I'm concerned `fn.misc.input()[item]` is not intuitive. Firstly, `input` is not very descriptive and seems to refer exclusively to mesh coordinates, which is why the `coord` function was there. Secondly, item selection would make more sense if it were: `fn.misc.coord[0]`, which is similar to what I had for `fn_gradient[0]` and related to #35.

Generally speaking, I'm not too concerned about deviating from the UW API if it makes sense in certain places. Eventually, this will all end up in underware and the creases will get ironed out. @lmoresi what do you think?

**Comment by lmoresi** [comment]
I am inclined to agree - the underworld coord function is there to replace most of the cases that required actual coordinates. There are some use-cases where a function does not take coordinates and the input() refers to whatever was passed in regardless.

Not everything that makes sense in underworld makes sense in quagmire though there are many similarities. We should not be enslaved by the underworld functions that were not designed with quagmire in mind.

On 26 Jun 2020, 9:59 AM +1000, Ben Mather <notifications@github.com>, wrote:

I like the conditional stuff, could you add a demo in the LazyFunctions tutorial<https://github.com/underworld-community/quagmire-examples-and-workflows/blob/master/Examples/Tutorial/Ex1b-QuagmireLazyFunctions.py>?

I'm concerned fn.misc.input()[item] is not intuitive. Firstly, input is not very descriptive and seems to refer exclusively to mesh coordinates, which is why the coord function was there. Secondly, item selection would make more sense if it were: fn.misc.coord[0], which is similar to what I had for fn_gradient[0] and related to #35<https://github.com/underworldcode/quagmire/pull/35>.

Generally speaking, I'm not too concerned about deviating from the UW API if it makes sense in certain places. Eventually, this will all end up in underware and the creases will get ironed out. @lmoresi<https://github.com/lmoresi> what do you think?

**Comment by rbeucher** [comment]
I think we can deviate while keeping them compatible. UW3 will show up at some point so compatibility with UW2 is probably not a top priority. It really depends on what we are planning to do in terms of research. I think there is plenty to do with Quagmire alone.
Happy to get the coords function back in. I am looking at it now.

**Comment by rbeucher** [comment]
I have revert the input() function

**Comment by lmoresi** [comment]
Shall we go ahead with this ?

**Pull request merged**
